import java.util.Map;

import static java.util.Map.entry;

public class TileInfo {

    static Map<String, Integer> tileFrequency = Map.ofEntries(entry("A", 9),
            entry("B", 2),
            entry("C", 2),
            entry("D", 4),
            entry("E", 12),
            entry("F", 2),
            entry("G", 3),
            entry("H", 2),
            entry("I", 9),
            entry("J", 1),
            entry("K", 1),
            entry("L", 4),
            entry("M", 2),
            entry("N", 6),
            entry("O", 8),
            entry("P", 2),
            entry("Q", 1),
            entry("R", 6),
            entry("S", 4),
            entry("T", 6),
            entry("U", 4),
            entry("V", 2),
            entry("W", 2),
            entry("X", 1),
            entry("Y", 2),
            entry("Z", 1),
            entry("_", 2));

    static Map<String, Integer> tileValue = Map.ofEntries(entry("A", 1),
            entry("B", 3),
            entry("C", 3),
            entry("D", 2),
            entry("E", 1),
            entry("F", 4),
            entry("G", 2),
            entry("H", 4),
            entry("I", 1),
            entry("J", 8),
            entry("K", 5),
            entry("L", 1),
            entry("M", 3),
            entry("N", 1),
            entry("O", 1),
            entry("P", 3),
            entry("Q", 10),
            entry("R", 1),
            entry("S", 1),
            entry("T", 1),
            entry("U", 1),
            entry("V", 4),
            entry("W", 4),
            entry("X", 8),
            entry("Y", 4),
            entry("Z", 10),
            entry("_", 0));

}
